apiVersion: v1
kind: ConfigMap
metadata:
  name: matchup-config
  namespace: matchup
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "matchup"
  DB_DRIVER: "postgres"
  PORT: "8888"
  APP_ENV: "production"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
